# Generated by Django 5.2.3 on 2025-06-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_pictures_plase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures_plase',
            name='image',
        ),
        migrations.AddField(
            model_name='pictures_plase',
            name='first_image',
            field=models.ImageField(blank=True, upload_to='static/images', verbose_name='Первая артинка'),
        ),
        migrations.AddField(
            model_name='pictures_plase',
            name='second_image',
            field=models.ImageField(blank=True, upload_to='static/images', verbose_name='Вторая картинка'),
        ),
    ]
