# Generated by Django 5.2.3 on 2025-06-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_pictures_plase_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures_plase',
            name='first_image',
        ),
        migrations.RemoveField(
            model_name='pictures_plase',
            name='second_image',
        ),
        migrations.AddField(
            model_name='pictures_plase',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images', verbose_name='Изображение места'),
        ),
    ]
