# Generated by Django 5.2.3 on 2025-06-26 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_pictures_plase_options_pictures_plase_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pictures_plase',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='pictures_plase',
            name='order',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Номер изображения'),
        ),
    ]
