# Generated by Django 5.2.3 on 2025-06-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_pictures_plase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures_plase',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение места'),
        ),
    ]
