# Generated by Django 5.2.3 on 2025-07-17 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_pictures_plase_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pictures_plase',
            new_name='Pictures_places',
        ),
    ]
