# Generated by Django 5.2.3 on 2025-07-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_rename_pictures_plase_pictures_places'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pictures_places',
            options={'ordering': ['order'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
    ]
