# Generated by Django 5.2.3 on 2025-08-30 17:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_place_description_long'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение места')),
                ('order', models.PositiveIntegerField(db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер изображения')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='places.place')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Pictures_places',
        ),
    ]
